import { useState } from 'react';
import type { Lead } from '../types/lead.types';
import { submitHumanReview } from '../api/leads.api';
import { StatusBadge } from './StatusBadge';
import { LiquidButton } from './ui/liquid-glass-button';

interface LeadDetailPanelProps {
  lead: Lead;
  onClose: () => void;
  onReviewed: () => void;
}

/**
 * LeadDetailPanel — shows full AI output AND the human review form
 *
 * Professor Note: this component is the visible proof of your
 * Responsible AI design from Phase 1. The aiAnalysis.responsibleAICaution
 * field, generated by the AI itself, is displayed directly to the human
 * reviewer right next to the form where they confirm or override it.
 * This is "human-in-the-loop" made literal and visible, not just a
 * line in documentation.
 */
export function LeadDetailPanel({ lead, onClose, onReviewed }: LeadDetailPanelProps) {
  const [reviewerName, setReviewerName] = useState('');
  const [overrideScore, setOverrideScore] = useState('');
  const [notes, setNotes] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [reviewError, setReviewError] = useState<string | null>(null);

  async function handleReviewSubmit() {
    if (!reviewerName.trim()) {
      setReviewError('Reviewer name is required');
      return;
    }
    const parsedOverride =
      overrideScore.trim() === '' ? undefined : Number(overrideScore);
    if (
      parsedOverride !== undefined &&
      (!Number.isFinite(parsedOverride) || parsedOverride < 0 || parsedOverride > 100)
    ) {
      setReviewError('Override score must be a number between 0 and 100');
      return;
    }

    setSubmitting(true);
    setReviewError(null);

    try {
      await submitHumanReview(lead.id, {
        humanReviewedBy: reviewerName,
        humanOverrideScore: parsedOverride,
        humanNotes: notes || undefined,
      });
      onReviewed();
    } catch (err) {
      setReviewError(
        err instanceof Error ? err.message : 'Failed to submit review'
      );
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="detail-overlay" onClick={onClose}>
      <div className="detail-panel" onClick={(e) => e.stopPropagation()}>
        <LiquidButton className="detail-close absolute right-4 top-4 bg-transparent border-none shadow-none text-gray-500 hover:text-black hover:bg-gray-100" onClick={onClose}>✕</LiquidButton>

        <h2>{lead.company}</h2>
        <StatusBadge
          status={lead.status}
          category={lead.aiAnalysis?.leadScore.category}
        />

        {lead.status === 'pending' && (
          <p className="detail-pending">AI analysis in progress…</p>
        )}

       {lead.status === 'failed' && (
  <p className="detail-failed">
    {lead.failureReason?.startsWith('GEMINI_UNAVAILABLE')
      ? "⚠ The AI service is temporarily overloaded on Google's end. This is not an issue with your data - try resubmitting in a few minutes."
      : `Analysis failed: ${lead.failureReason}`}
  </p>
)}

        {lead.aiAnalysis && (
          <>
            <section>
              <h3>Score: {lead.aiAnalysis.leadScore.score}/100</h3>
              <p>{lead.aiAnalysis.leadScore.reasoning}</p>
              <p><em>Confidence: {lead.aiAnalysis.leadScore.confidenceLevel}</em></p>
            </section>

            <section>
              <h3>Pain Point</h3>
              <p>{lead.aiAnalysis.identifiedPainPoint}</p>
            </section>

            <section>
              <h3>Draft Email</h3>
              <p><strong>{lead.aiAnalysis.outreach.firstEmail.subject}</strong></p>
              <p>{lead.aiAnalysis.outreach.firstEmail.body}</p>
            </section>

            <section>
              <h3>LinkedIn Message</h3>
              <p>{lead.aiAnalysis.outreach.linkedinMessage}</p>
            </section>

            <section>
              <h3>Follow-up</h3>
              <p>
                {lead.aiAnalysis.outreach.followUpAction} (in{' '}
                {lead.aiAnalysis.outreach.followUpDays} days)
              </p>
            </section>

            <section>
              <h3>CRM Note</h3>
              <p>{lead.aiAnalysis.crmNote}</p>
            </section>

            <section className="responsible-ai-note">
              <h3>⚠ Responsible AI Caution</h3>
              <p>{lead.aiAnalysis.responsibleAICaution}</p>
              {lead.aiAnalysis.missingInformation.length > 0 && (
                <p>
                  Missing info: {lead.aiAnalysis.missingInformation.join(', ')}
                </p>
              )}
            </section>
          </>
        )}

        <hr />

        <section className="review-section">
          <h3>Human Review</h3>
          {lead.humanReviewed ? (
            <div>
              <p>✓ Reviewed by {lead.humanReviewedBy}</p>
              {lead.humanOverrideScore !== undefined && (
                <p>Override score: {lead.humanOverrideScore}</p>
              )}
              {lead.humanNotes && <p>Notes: {lead.humanNotes}</p>}
            </div>
          ) : (
            <div className="review-form">
              <label>
                Reviewer Name
                <input
                  value={reviewerName}
                  onChange={(e) => setReviewerName(e.target.value)}
                />
              </label>
              <label>
                Override Score (optional)
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={overrideScore}
                  onChange={(e) => setOverrideScore(e.target.value)}
                />
              </label>
              <label>
                Notes (optional)
                <textarea
                  rows={2}
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                />
              </label>
              {reviewError && <p className="form-error">{reviewError}</p>}
              <LiquidButton onClick={handleReviewSubmit} disabled={submitting}>
                {submitting ? 'Submitting…' : 'Confirm Review'}
              </LiquidButton>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}